name: Update GIF Daily

permissions:
  contents: write   # allow pushing commits

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # fetch full history for pushing
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pick a random GIF
        run: |
          gifs=(assets/gifs/*.gif)
          echo "Found ${#gifs[@]} gifs"
          random_gif=${gifs[$RANDOM % ${#gifs[@]}]}
          echo "RANDOM_GIF=$random_gif" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i -E "/<!--START_SECTION:gif-->/, /<!--END_SECTION:gif-->/c\\<!--START_SECTION:gif-->\n<img src=\"./$RANDOM_GIF\" width=\"300\" align=\"right\">\n<!--END_SECTION:gif-->" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update random GIF"
            git push origin HEAD:main
          fi
